# Storage class to use for persistent volumes
storageClassName: my-azure-storageclass

coordinator:
  persistentVolume:
    accessModes:
      - ReadWriteOnce
    size: 128Gi

manager:
  # put it on the same node as coordinator
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values: ["coordinator"]
          topologyKey: kubernetes.io/hostname

worker:
  replicas: 2
  persistentVolume:
    accessModes:
      - ReadWriteOnce
    size: 128Gi
  # # Anti-affinity to ensure each worker runs on separate node
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values: ["manager", "coordinator", "worker"]
          topologyKey: kubernetes.io/hostname

postgres:
  user: researcher
  password: bachelorthesis
  database: postgres

# Internal service configuration
service:
  type: ClusterIP
  port: 5432

# External service for load generator access
externalService:
  enabled: true
  type: LoadBalancer
  name: mobilitydb-external-service
  port: 5432
  portName: postgres
