# ---------------------------
# Coordinator Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobilitydbc-benchmark.fullname" . }}-coordinator
  labels:
    {{- include "mobilitydbc-benchmark.labels" . | nindent 4 }}
    component: coordinator
spec:
  selector:
    {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 4 }}
    component: coordinator
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
---
# ---------------------------
# Coordinator StatefulSet
# ---------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mobilitydbc-benchmark.fullname" . }}-coordinator
  labels:
    {{- include "mobilitydbc-benchmark.labels" . | nindent 4 }}
    component: coordinator
spec:
  serviceName: {{ include "mobilitydbc-benchmark.fullname" . }}-coordinator
  replicas: {{ .Values.coordinator.replicas }}
  selector:
    matchLabels:
      {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 6 }}
      component: coordinator
  template:
    metadata:
      labels:
        {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 8 }}
        component: coordinator
    spec:
      containers:
        - name: coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: CITUS_ROLE
              value: coordinator
          ports:
            - containerPort: 5432
              protocol: TCP
          {{- with .Values.coordinator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.coordinator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
