# ---------------------------
# Worker Headless Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobilitydbc-benchmark.fullname" . }}-worker
  labels:
    {{- include "mobilitydbc-benchmark.labels" . | nindent 4 }}
    component: worker
spec:
  clusterIP: None
  selector:
    {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 4 }}
    component: worker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
---
# ---------------------------
# Worker StatefulSet
# ---------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mobilitydbc-benchmark.fullname" . }}-worker
  labels:
    {{- include "mobilitydbc-benchmark.labels" . | nindent 4 }}
    component: worker
spec:
  serviceName: {{ include "mobilitydbc-benchmark.fullname" . }}-worker
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "mobilitydbc-benchmark.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: CITUS_ROLE
              value: worker
          ports:
            - containerPort: 5432
              protocol: TCP
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
