version: '3.8'

services:
  crate01:
    image: crate
    container_name: crate01
    environment:
      - CRATE_HEAP_SIZE=1g
    command: >
      crate
      -Cnetwork.host=_site_
      -Cdiscovery.type=single-node
    ports:
      - "4201:4200"
    networks:
      - crate

networks:
  crate:
    driver: bridge
