# CrateDB internal service
# This is the service that each CrateDB node be able to discover and
# communicate with the other nodes in the cluster.
apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.internalService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cratedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.internalService.type }}
  ports:
    - port: {{ .Values.internalService.port }}
      targetPort: {{ .Values.internalService.port }}
      protocol: TCP
      name: {{ .Values.internalService.portName }}
  selector:
    {{- include "cratedb.selectorLabels" . | nindent 4 }}
