apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: ba-cratedb-cluster
  namespace: default
spec:
  cluster:
    imageRegistry: crate
    name: crate-cluster
    version: {{ .Values.version }}
  nodes:
    data:
      - name: hot
        replicas: {{ .Values.replicas }}
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}
