replicas: 3

version: 5.10.11

resources:
  requests:
    cpu: 2
    memory: "10Gi"
  limits:
    cpu: 4
    memory: "16Gi"
  disk:
    count: 1
    size: 128GiB
    storageClass: my-azure-storageclass
  heapRatio: 0.25
