# Default values for mobilitydbc-cluster
nameOverride: ""
fullnameOverride: ""

coordinator:
  replicas: 1
  resources: {}
  # Anti-affinity to ensure coordinator runs on separate node from workers only
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values: ["worker"]
          topologyKey: kubernetes.io/hostname

manager:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values: ["coordinator"]
          topologyKey: kubernetes.io/hostname

worker:
  replicas: 1
  resources: {}
  # Anti-affinity to ensure each worker runs on separate node
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values: ["manager", "coordinator", "worker"]
          topologyKey: kubernetes.io/hostname

postgres:
  user: postgres
  password: postgres
  database: postgres

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: false
  hosts: []
  tls: false
