# ---------------------------
# Coordinator Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: mobilitydbc-coordinator-service
  labels:
    {{- include "mobilitydbc-cluster.labels" . | nindent 4 }}
    component: coordinator
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 4 }}
    component: coordinator
---
# ---------------------------
# Coordinator StatefulSet
# ---------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mobilitydbc-coordinator
  labels:
    {{- include "mobilitydbc-cluster.labels" . | nindent 4 }}
    component: coordinator
spec:
  serviceName: mobilitydbc-coordinator
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  selector:
    matchLabels:
      {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 6 }}
      component: coordinator
  template:
    metadata:
      labels:
        {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 8 }}
        component: coordinator
    spec:
      containers:
        - name: coordinator
          image: "ghcr.io/erykksc/citus-mobilitydb:latest"
          imagePullPolicy: Always 
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: CITUS_ROLE
              value: coordinator
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            # PostgreSQL performance tuning for MobilityDB
            - name: POSTGRES_INITDB_ARGS
              value: "-c statement_timeout=300000 -c work_mem=512MB -c shared_buffers=2GB -c max_connections=1010"
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
        labels:
          {{- include "mobilitydbc-cluster.labels" . | nindent 10 }}
          component: coordinator
      spec:
        accessModes:
          {{- toYaml .Values.coordinator.persistentVolume.accessModes | nindent 10 }}
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.coordinator.persistentVolume.size }}
