# ---------------------------
# Worker Headless Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: mobilitydbc-worker
  labels:
    {{- include "mobilitydbc-cluster.labels" . | nindent 4 }}
    component: worker
spec:
  clusterIP: None
  selector:
    {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 4 }}
    component: worker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
---
# ---------------------------
# Worker StatefulSet
# ---------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mobilitydbc-worker
  labels:
    {{- include "mobilitydbc-cluster.labels" . | nindent 4 }}
    component: worker
spec:
  serviceName: mobilitydbc-worker
  replicas: {{ .Values.worker.replicas }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  selector:
    matchLabels:
      {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "mobilitydbc-cluster.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: worker
          image: "ghcr.io/erykksc/citus-mobilitydb:latest"
          imagePullPolicy: Always 
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: CITUS_ROLE
              value: worker
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            # PostgreSQL performance tuning for MobilityDB
            - name: POSTGRES_INITDB_ARGS
              value: "-c statement_timeout=300000 -c work_mem=512MB -c shared_buffers=2GB -c max_connections=1010"
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgresql-data
          emptyDir:
            medium: ""  # Use node filesystem instead of memory
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
